google:
   client:
      clientId: 299246322347-t9rahd5i7tck8fp826en1kk2d353scsj.apps.googleusercontent.com
      clientSecret: BUrAEbCS9wiNNMeHDNOANKbJ
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      preEstablishedRedirectUri: http://sdi.myftp.org:81/login/google
      useCurrentUri: false
      
      scope:
         - email
         - profile
         - https://www.googleapis.com/auth/drive
      
   resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true